number1 = (input("Enter number 1: "))
print(number1)
number2 = (input("Enter number 2: "))
print(number2)
symbol = (input("Enter symbol:"))
print(symbol)
calulate = (eval(number1+symbol+number2))
print(calulate)
